In [ ]:
import numpy as np

# File path
file_path = '/content/drive/MyDrive/Colab Notebooks/testmarks1.csv'

# Read the file using np.genfromtxt()
dataset = np.genfromtxt(file_path, delimiter=',', dtype=float,
skip_header=1)

# Matrix operations
dataset_transpose = dataset.T
matrix_product = np.dot(dataset_transpose, dataset)
matrix_inverse = np.linalg.inv(matrix_product)

# Horizontal and vertical stacking
hor_stack = np.hstack(dataset)
ver_stack = np.vstack(dataset)

# Custom sequence generation
custom_sequence = np.arange(0, len(dataset), 2)

# Arithmetic and Statistical Operations
addition = dataset[:, 1] + dataset[:, 2]
subtraction = dataset[:, 3] - dataset[:, 4]
multiplication = dataset[:, 1] * dataset[:, 3]
division = dataset[:, 2] / dataset[:, 4]
mean_col1 = np.mean(dataset[:, 1])
median_col2 = np.median(dataset[:, 2])
std_dev_col3 = np.std(dataset[:, 3])
max_col4 = np.max(dataset[:, 4])
min_col5 = np.min(dataset[:, 4])

# Mathematical Operations
exponential = np.exp(dataset[:, 1])
sqrt_col2 = np.sqrt(dataset[:, 2])
log_col3 = np.log(dataset[:, 3])

# Bitwise Operators
bitwise_and = np.bitwise_and(dataset[:, 2].astype(int), dataset[:,
4].astype(int))
bitwise_or = np.bitwise_or(dataset[:, 2].astype(int), dataset[:,
4].astype(int))

# Copying and Viewing Arrays
copy_col1 = np.copy(dataset[:, 1])
view_col3 = dataset[:, 3].view()

# Data Stacking
col_stack = np.column_stack((dataset[:, 1], dataset[:, 3]))
row_stack = np.row_stack((dataset[:, 2], dataset[:, 4]))

# Searching
index = np.where(dataset[:, 1] == 28.63)

# Sorting
sorted_col2 = np.sort(dataset[:, 2])

# Counting
count_col4 = np.count_nonzero(dataset[:, 4])

# Broadcasting
broadcasted_col1 = dataset[:, 1] * 2

# Print the results
print("Dataset Transpose:\n", dataset_transpose)
print("Matrix Product:\n", matrix_product)
print("Matrix Inverse:\n", matrix_inverse)
print("Horizontal Stack:\n", hor_stack)
print("Vertical Stack:\n", ver_stack)
print("Custom Sequence:\n", custom_sequence)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)
print("Mean of Column 1:", mean_col1)
print("Median of Column 2:", median_col2)
print("Standard Deviation of Column 3:", std_dev_col3)
print("Maximum of Column 4:", max_col4)
print("Minimum of Column 5:", min_col5)
print("Exponential of Column 1:\n", exponential)
print("Square Root of Column 2:\n", sqrt_col2)
print("Logarithm of Column 3:\n", log_col3)
print("Bitwise AND of Column 2 and Column 4:\n", bitwise_and)
print("Bitwise OR of Column 2 and Column 4:\n", bitwise_or)
print("Copy of Column 1:\n", copy_col1)
print("View of Column 3:\n", view_col3)
print("Column Stack:\n", col_stack)
print("Row Stack:\n", row_stack)
print("Index of 28.63 in Column 1:", index)
print("Sorted Column 2:\n", sorted_col2)
print("Count of Nonzero values in Column 4:", count_col4)
print("Broadcasted Column 1:\n", broadcasted_col1)

Dataset Transpose:
 [[801.   802.   803.   804.   805.   806.   807.   808.   809.   810.  ]
 [ 43.05  43.47  42.24  39.24  40.9   39.47  41.68  42.19  44.75  46.95]
 [ 27.79  28.52  28.16  26.16  26.03  26.31  25.63  27.61  28.35  28.88]
 [ 28.7   28.98  28.16  26.16  27.27  26.31  27.79  28.13  29.83  31.3 ]
 [ 27.79  27.89  25.63  26.16  25.65  25.21  25.46  26.21  28.21  28.53]]
Matrix Product:
 [[6488385.      341508.52    220258.2     227675.03    214863.7   ]
 [ 341508.52     18021.713    11612.9062   12014.6105   11330.8448]
 [ 220258.2      11612.9062    7489.7686    7742.0195    7304.6357]
 [ 227675.03     12014.6105    7742.0195    8009.8305    7553.9762]
 [ 214863.7      11330.8448    7304.6357    7553.9762    7129.786 ]]
Matrix Inverse:
 [[ 1.17576501e-04  4.95016743e-01 -3.10426698e-03 -7.41022093e-01
  -1.94704460e-03]
 [ 4.95016743e-01  1.12307998e+04 -1.90598939e+01 -1.68249731e+04
  -1.76916945e+01]
 [-3.10426698e-03 -1.90598939e+01  2.94944007e-01  2.84496142e+01
  -